In [1]:
# pip3 install scikit-learn

In [2]:
import pandas

In [3]:
db = pandas.read_csv('marks.csv')

In [4]:
# Taget / Dependent Variable
y = db['marks']

In [5]:
# Feature / Independent Variable
x = db['hrs']

In [6]:
from os import system

In [1]:
from sklearn.linear_model import LinearRegression

In [8]:
mind = LinearRegression()

In [9]:
x.shape

(4,)

In [10]:
type(x)

pandas.core.series.Series

In [11]:
import numpy

In [12]:
x = x.values

In [13]:
type(x)

numpy.ndarray

In [18]:
x = x.reshape(4,1)

In [19]:
x.shape

(4, 1)

In [20]:
x

array([[7],
       [5],
       [8],
       [2]])

In [21]:
# Experience : Model : Linear Function
# w: weight / Coefficient
# model trained
mind.fit(x, y)

LinearRegression()

In [25]:
mind.predict([[ 6 ]])

array([60.])

In [27]:
# Linear Function : y = wx
# w = 10

mind.coef_

array([10.])

In [28]:
# Save Model

import joblib

In [29]:
joblib.dump(mind , 'marks.pk1')

['marks.pk1']